[tox]
envlist = {py310,py313,py314}-{tests,cli},lint
skip_missing_interpreters = true

[testenv]
allowlist_externals =
    cli:   {[testenv:cli]allowlist_externals}
deps=
    tests:      {[testenv:tests]deps}
    lint:       {[testenv:lint]deps}
commands=
    tests:      {[testenv:tests]commands}
    lint:       {[testenv:lint]commands}
    cli:        {[testenv:cli]commands}

[testenv:tests]
deps=
    pytest
    pytest-cov
commands=
    pytest {posargs}

[testenv:lint]
basepython=python3
deps=
    pylint
    ruff
    isort
commands=
    pylint iotlabwebsocket
    ruff check .
    ruff format --check .
    isort --check-only .

[testenv:cli]
allowlist_externals=
    /bin/bash
    /usr/bin/bash
commands=
    bash -exc "iotlab-websocket-service --help > /dev/null"
